[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PyDrag"
authors = [{name = "IRSN", email = "toto@irsn.fr"}]
dynamic = ["version", "description"]
